### ISSUE TITLE
Change titile for home page

### ISSUE THREAD

**Issue by ppalit** [ppalit/sample-laf#1]
Tilte of home page shows Bootstrap 101.

![image](https://cloud.githubusercontent.com/assets/10590336/6452068/09fa12b4-c101-11e4-8f4f-c2b099ac0468.png)

**Comment by SidKB** [comment]
magya!!!!! chus lo

**Comment by ppalit** [comment]
please keep it proffesional

**Comment by SidKB** [comment]
Fixed
